### ISSUE TITLE
[BE][FEAT] 마이페이지 사용자 프로필 조회

### ISSUE THREAD

**Issue by LYJ22** [hyundai-autoever-second-project-team4/Review-BE#43]
## 💻 Feature 설명
> 마이페이지에서 사용자의 프로필 부분을 조회합니다.
<br>

## 📝 To-do
**api 내용**
- [ ] 대표배지에 따른 배경 이미지 경로
- [ ] 멤버 이름
- [ ] 멤버 프로필 사진 경로
- [ ] 멤버 티어 이미지
- [ ] 멤버 대표배지 아이디
- [ ] 멤버 획득 뱃지 배열 또는 리스트
- [ ] 멤버 티어 이름
- [ ] 멤버 현재 티어에서 다음 티어까지 채워야 하는 총 점수 & 멤버가 획득한 점수
<br>

## 📸 스크린샷
![image](https://github.com/user-attachments/assets/0d7247eb-1f5d-4efa-aa7c-effaf42923a8)

<br>

## 📚 참고문헌 / 기타
-
