### ISSUE TITLE
[BE][FEAT] 사용자 티어 기능 구현

### ISSUE THREAD

**Issue by pjm2571** [hyundai-autoever-second-project-team4/Review-BE#53]
## 💻 Feature 설명
> 사용자의 활동 정보에 따른 점수 및 티어 기능 구현
<br>

## 📝 To-do
**사용자 점수 기능 구현**
- [x] 사용자가 작성한 리뷰 수에 따른 점수 기능 구현
- [x] 사용자가 받은 좋아요 수에 대한 점수 기능 구현
- [x] 사용자가 작성한 댓글 수에 따른 점수 기능 구현

**사용자 티어 기능 구현**
- [x] 사용자의 점수 분포에 따른 티어 기능 구현
<br>

## 📸 스크린샷
<img width="591" alt="image" src="https://github.com/user-attachments/assets/d16ead7f-e8c4-4cce-8345-a6da84962e7e">

<br>

## 📚 참고문헌 / 기타
-
