### ISSUE TITLE
[BE][FEAT] 영화 id에 해당하는 리뷰 상세 조회 기능 구현

### ISSUE THREAD

**Issue by pjm2571** [hyundai-autoever-second-project-team4/Review-BE#65]
## 💻 Feature 설명
> 영화 id에 해당하는 review들을 모두 가져와서, 페이지네이션으로 전달하는 기능 구현
<br>

## 📝 To-do
**메인주제**
- [ ] 최신순으로 정렬해오는 메소드 구현
- [ ] 별점 높은 순으로 정렬해오는 메소드 구현
- [ ] 별점 낮은 순으로 정렬해오는 메소드 구현
- [ ] 댓글 많은 순으로 정렬해오는 메소드 구현
  - 선택 사항임!
<br>

## 📸 스크린샷
<img width="734" alt="image" src="https://github.com/user-attachments/assets/dd143826-f550-4676-b741-cfd9c53b538f">

<br>

## 📚 참고문헌 / 기타
-
