### ISSUE TITLE
[BE][FEAT] 리뷰 Create & Delte

### ISSUE THREAD

**Issue by pjm2571** [hyundai-autoever-second-project-team4/Review-BE#7]
## 💻 Feature 설명
> 리뷰를 작성하는 기능을 구현합니다.

- [x] 리뷰 생성 기능 구현
- [ ] 리뷰 생성 시, movie 정보가 반영되게 구현
- [x] 라뷰 삭제 기능 구현
- [ ] 리뷰 삭제 시, movie 정보가 반영되게 구현

<br>

## 📝 To-do
**메인주제**
- [x] 리뷰 CREATE 기능을 구현
- [x] 리뷰 DELETE 기능을 구현
- [x] 리뷰 SOFT DELETE 기능을 구현
<br>

## 📸 스크린샷
<img width="475" alt="image" src="https://github.com/user-attachments/assets/3a8d3104-6402-403b-91c3-bdd12735f8bb">

### 수정된 ERD
- `deleted (boolean)` 필드가 추가됨

<img width="185" alt="image" src="https://github.com/user-attachments/assets/ef841cd6-fa7f-45c3-9d39-f556f1824279">

<br>

## 📚 참고문헌 / 기타
-
