### ISSUE TITLE
[BE][FEAT] 영화 엔티티 생성 및 리뷰 생성&삭제 시, 영화 엔티티에 반영 기능 구현

### ISSUE THREAD

**Issue by pjm2571** [hyundai-autoever-second-project-team4/Review-BE#9]
## 💻 Feature 설명
> Movie 엔티티 생성을 구현합니다. 
Review가 생성될 때, Movie 필드의 total_review_count 값과 total_star_rate 값이 변경되도록 구현합니다.
Review가 삭제될 때, Movie 필드의 total_review_count 값과 total_star_rate 값이 변경되도록 구현합니다.
<br>

## 📝 To-do
**메인주제**
- [x] Movie 엔티티 구현하기
- [x] Review 삭제 시, Movie 필드 변경 작업 구현하기
- [x] Review 생성 시, Movie 필드 변경 작업 구현하기 
<br>

## 📸 스크린샷
<img width="376" alt="image" src="https://github.com/user-attachments/assets/b3b8d633-a12e-43cb-99fa-e4e87031edd5">

<br>

## 📚 참고문헌 / 기타
-
